# Generated by Django 6.1 on 2026-08-17 19:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convertion',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3adc438c-32d4-4631-b0d8-94b254c4082f'), editable=False, primary_key=True, serialize=False)),
                ('old_link', models.CharField(max_length=500)),
                ('new_link', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('46ad2315-5c61-48f1-b299-b279c94f1a9b'), editable=False, primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='home.convertion')),
            ],
        ),
    ]
